// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package database

import (
	"context"
)

const getAuthor = `-- name: GetAuthor :many
SELECT id, name, birthday, gender FROM actors
`

func (q *Queries) GetAuthor(ctx context.Context) ([]Actor, error) {
	rows, err := q.db.Query(ctx, getAuthor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Actor
	for rows.Next() {
		var i Actor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Birthday,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
