openapi: 3.0.3
info:
  title: Vk Internship Secs
  description: |-
    This is api specification for my project
  version: 1.0.0

servers:
  - url: http://127.0.0.1:80/
tags:
  - name: film
    description: Working with films
  - name: actor
    description: Working with actors
  - name: user
    description: Everything connected to auth/sessions
paths:
  /film/get:
    get:
      tags:
        - film
      summary: Returns all the films from database
      description: Return films by order specified in query
      security:
        - BasicAuth: [User]
      parameters:
        - in: query
          name: sortBy
          schema:
            type:
              string
            enum:
              - Rating
              - Title
              - ReleaseDate

            required: false
        - in: query
          name: sortType
          schema:
            type:
              string
            enum:
              - desc
              - asc
            required: false

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Films'
        '400':
          description: No film with this Id
        '401':
          description: Unauthorized
        '500':
          description: Internal error

  /film/search:
    get:
      tags:
        - film
      summary: Allow you to find film with specified actor
      description: You can find film using it's Title and actor's Name
      security:
        - BasicAuth: [ User ]
      parameters:
        - in: query
          name: actor
          schema:
            type:
              string
        - in: query
          name: Title
          schema:
            type:
              string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film' # change
        '401':
          description: Unauthorized
        '404':
          description: Film not found
        '500':
          description: Internal error
  /film/create:
    put:
      tags:
        - film
      summary: Create new film
      description: Allow admin to create new film
      security:
        - BasicAuth: [ Admin ]
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewFilm'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                    format: int32
        '400':
          description: One or more parameters weren't provIded
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  /film/update:
    post:
      tags:
        - film
      summary: Update a film by Id
      description: Allow admin to update film
      security:
        - BasicAuth: [ Admin ]
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Film' # change
      responses:
        '200':
          description: Successful operation
        '400':
          description: Wrong data provIded
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  
  /film/delete:
    delete:
      tags:
        - film
      summary: Delete film by Id
      description: Allow admin to delete a film by Id
      security:
        - BasicAuth: [ Admin ]
      parameters:
        - in: query
          name: Id
          schema:
            type:
              integer
      responses:
        '200':
          description: Successful operation
        '400':
          description: No film with that Id
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  
  /actor/get:
    get:
      tags:
        - actor
      summary: Get actor by Id
      description: Allow user to get actor with Id specified in query
      security:
        - BasicAuth: [ User ]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Actor' # change
        '401':
          description: Unauthorized
        '404':
          description: Actor not found
        '500':
          description: Internal error
  
  /actor/get_with_films:
    get:
      tags:
        - actor
      summary: Get all actors with films
      description: Allow user to get all actors with films
      security:
        - BasicAuth: [ User ]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorsWithFilms' # change
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  /actor/create:
    put:
      tags:
        - actor
      summary: Create new actor
      description: Allow admin to create new film
      security:
        - BasicAuth: [ Admin ]
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewActor' # change
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                    format: int32
        '400':
          description: Wrong data provIded
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  /actor/update:
    post:
      tags:
        - actor
      summary: Update an actor
      description: Allow admin to update info about the actor
      security:
        - BasicAuth: [ Admin ]
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Actor' # change
      responses:
        '200':
          description: Successful operation
        '400':
          description: No properties was changed
        '401':
          description: Unauthorized
        '500':
          description: Internal error

  /actor/delete:
    delete:
      tags:
        - actor
      summary: Delete film
      description: Allow admin to delete the actor
      security:
        - BasicAuth: [ Admin ]
      parameters:
        - in: query
          name: Id
          schema:
            type:
              integer
      responses:
        '200':
          description: Successful operation
        '400':
          description: No actor was found with that Id
        '401':
          description: Unauthorized
        '500':
          description: Internal error
  
  
  /user/register:
    post:
      tags:
        - user
      summary: Create user
      description: Allow anybody to register in
      
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'

      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: string
                    format: uuId


  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: 'Login'
      operationId: loginUser
      parameters:
        - name: userName
          in: query
          description: The user Name for login
          required: false
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:

            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

        '400':
          description: InvalId userName/password supplied

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: bearer
  schemas:
    Films:
      type: array
      items:
        $ref: '#/components/schemas/Film'
    Film:
      type: object
      properties:
        Id:
          type: integer
          format: int32
        Title:
          type: string
          example: "Titanic"
        Description:
          type: string
          example: "Good film"
        ReleaseDate:
          type: string
          format: date
        Rating:
          type: integer
          format: int8
    NewFilm:
      type: object
      properties:
        Title:
          type: string
          example: "Titanic"
        Description:
          type: string
          example: "Good film"
        ReleaseDate:
          type: string
          format: date
        Rating:
          type: integer
          format: int8
        actors:
            type: array
            items:
                type: integer
            example: [1, 2]
    Actor:
      type: object
      properties:
        Id:
          type: integer
          format: int32
        Name:
          type: string
          example: "Pavel Snezhok Volya"
        Birthday:
          type: string
          format: date
        Gender:
          type: string
          enum:
            - male
            - female
    NewActor:
      type: object
      properties:
        Name:
          type: string
          example: "Pavel Snezhok Volya"
        Birthday:
          type: string
          format: date
        Gender:
          type: string
          enum:
            - male
            - female

    NewUser:
      type: object
      properties:
        Id:
          type: string
          format: login
          example: "MyLogin"
        email:
          type: string
          format: email
          example: john@email.com
        password:
          type: string
          format: password
          example: '12345'
    ActorsWithFilms:
      type: array
      items:
        type: object
        properties:
          actor:
            type: object
            properties:
              Id:
                type: integer
                format: int32
              Name:
                type: string
                example: "Pavel Snezhok Volya"
              Birthday:
                type: string
                format: date
              Gender:
                type: string
                enum:
                  - male
                  - female
          films:
            type: array
            items:
              type: object
              properties:
                Id:
                  type: integer
                  format: int32
                Title:
                  type: string
                  example: "Titanic"
                Description:
                  type: string
                  example: "Good film"
                ReleaseDate:
                  type: string
                  format: date
                Rating:
                  type: integer
                  format: int8